global:
  ##############################
  storageClassName: "csi-cephfs-sc"
  hosts:
    services: ""
    web: ""
  basicAuth: false

########## SECRETS ###########
secrets:
  sql:
    name: sql-secret
    acid:  
      secretKey: acidConnectionString
    base:
      secretKey: baseConnectionString
    oauth:
      secretKey: oauthConnectionString
  virtuoso:
    name: virtuoso-secret
    read:
      secretKey: virtuosoRead
    readHome:
      secretKey: virtuosoReadHome    
    writeHome:
      secretKey: virtuosoWriteHome
    write1:
      secretKey: virtuosoWrite1
    write2:
      secretKey: virtuosoWrite2
  rabbitmq:
    name: rabbitmq-secret
    connectionString:
      secretKey: rabbitMQConnectionString
  identity:
    name: identity-secret
    scope: 
      secretKey: scope
    clientID: 
      secretKey: clientID
    clientSecret:
      secretKey: clientSecret
  tls:
    secretName: tls-secret
  basicAuth:
    name: basic-auth-secret

################################
#                              #
#    VALUES PARA LOS INGRESS   #
#                              #
################################
ingress:
  https: true
  schema_servicios: "https"
  forwardedheaders: true

###########################
#                         #
#    VALUES COMUNES       #
#                         #
###########################
general:
  tag: "6.1.19"
  extraTolerations: null
  # extraTolerations will be appended to service specific tolerations
  # extraTolerations:
  #   - key: "team"
  #     operator: "Equal"
  #     value: "gnoss"
  #     effect: "NoSchedule"
  extraAffinity: null
  # extraAffinity will be merged with service specific affinity
  # extraAffinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: kubernetes.io/hostname
  #           operator: NotIn
  #           values:
  #           - master0
  #           - master1
  #           - master2
  imagePullSecrets: null
  user: 2000
  group: 2000
  connectionType: "2"
  language: "es|Español,en|English,ca|Català,eu|Euskara,gl|Galego"
  replicacionActivada: true
  replicacionActivadaHome: true
  apiPort: 8080
  managementPort: 8081
  healthChecksEnabled: true

######################################
#                                    #
#     VALUES PARA SERVICIOS WEB      #
#                                    #
######################################

# Para crear referencias de values sobre el mismo values
#template-front: "{{ .Values.version-front }}"
#version-front: "5.15.7"

web:
  replicas: 1
  image: "gnoss/gnoss.web.opencore"
  tag: ""
  pullPolicy: IfNotPresent
  limitsEnabled: true
  limitMemory: 6000Mi
  limitCpu: 4
  requestMemory: 300Mi
  requestCpu: 200m
  restartPolicy: Always
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"
  robotsTxt: |
    User-agent: *
    Disallow: /

login:
  replicas: 1
  image: "gnoss/gnoss.web.login.opencore"
  tag: ""
  pullPolicy: IfNotPresent
  limitsEnabled: true
  limitMemory: 600Mi
  limitCpu: 2
  requestMemory: 200Mi
  requestCpu: 100m
  restartPolicy: Always
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"

facetas:
  replicas: 1
  image: "gnoss/gnoss.web.facets.opencore"
  tag: ""
  pullPolicy: IfNotPresent
  limitsEnabled: true
  limitMemory: 800Mi
  limitCpu: 2
  requestMemory: 200Mi
  requestCpu: 100m
  restartPolicy: Always
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"

results:
  replicas: 1
  image: "gnoss/gnoss.web.results.opencore"
  tag: ""
  pullPolicy: IfNotPresent
  limitsEnabled: true
  limitMemory: 800Mi
  limitCpu: 2
  requestMemory: 200Mi
  requestCpu: 100m
  restartPolicy: Always
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"

autocompletar:
  replicas: 1
  image: "gnoss/gnoss.web.autocomplete.opencore"
  tag: ""
  pullPolicy: IfNotPresent
  limitsEnabled: true
  limitMemory: 500Mi
  limitCpu: 2
  requestMemory: 100Mi
  requestCpu: 100m
  restartPolicy: Always
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"

despliegues:
  replicas: 1
  image: "gnoss/gnoss.web.deploy.opencore"
  tag: ""
  pullPolicy: IfNotPresent
  limitsEnabled: true
  limitMemory: 500Mi
  limitCpu: 2
  requestMemory: 100Mi
  requestCpu: 100m
  restartPolicy: Always
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"

api:
  replicas: 1
  image: "gnoss/gnoss.web.api.opencore"
  tag: ""
  pullPolicy: IfNotPresent
  limitsEnabled: true
  limitMemory: 1Gi
  limitCpu: 4
  requestMemory: 125Mi
  requestCpu: 100m
  restartPolicy: Always
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"

oauth:
  replicas: 1
  image: "gnoss/gnoss.web.oauth.opencore"
  tag: ""
  debugNodePort: 30011
  pullPolicy: IfNotPresent
  rateLimitPermitLimit: "2000"
  limitsEnabled: true
  limitMemory: 800Mi
  limitCpu: 2
  requestMemory: 125Mi
  requestCpu: 100m
  restartPolicy: Always
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"

identityserver:
  replicas: 1
  image: "gnoss/gnoss.web.identityserver.opencore"
  tag: ""
  debugNodePort: 30013
  pullPolicy: IfNotPresent
  limitsEnabled: true
  limitMemory: 500Mi
  limitCpu: 500m
  requestMemory: 100Mi
  requestCpu: 100m
  restartPolicy: Always
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"

etiquetadoautomatico:
  replicas: 1
  image: "gnoss/gnoss.web.labeler.opencore"
  tag: ""
  pullPolicy: IfNotPresent
  limitsEnabled: true
  limitMemory: 200Mi
  limitCpu: 2
  requestMemory: 100Mi
  requestCpu: 100m
  restartPolicy: Always
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"

###########################################
#                                         #
#    VALUES PARA SERVICIOS STATEFULSET    #
#                                         #
###########################################
generalstatefulset:
  pullPolicy: IfNotPresent

documents:
  replicas: 1
  image: "gnoss/gnoss.web.documents.opencore"
  tag: ""
  debugNodePort: 30009
  limitsEnabled: true
  limitMemory: 800Mi
  limitCpu: 2
  requestMemory: 125Mi
  requestCpu: 100m
  restartPolicy: Always
  espacioVol: "5Gi"
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"

interno:
  replicas: 1
  image: "gnoss/gnoss.web.intern.opencore"
  tag: ""
  debugNodePort: 30007
  limitsEnabled: true
  limitMemory: 800Mi
  limitCpu: 500m
  requestMemory: 125Mi
  requestCpu: 100m
  restartPolicy: Always
  espacioVol: "5Gi"
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"

ontologias:
  replicas: 1
  image: "gnoss/gnoss.web.ontologies.opencore"
  tag: ""
  debugNodePort: 30008
  limitsEnabled: true
  limitMemory: 500Mi
  limitCpu: 500m
  requestMemory: 125Mi
  requestCpu: 100m
  restartPolicy: Always
  espacioVol: "5Gi"
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"
  
visitregistry:
  replicas: 1
  image: "gnoss/gnoss.backgroundtask.visitregistry.opencore"
  tag: ""
  pullPolicy: IfNotPresent
  limitsEnabled: true
  limitCpu: 500m
  limitMemory: 600Mi
  requestCpu: 50m
  restartPolicy: Always
  requestMemory: 125Mi
  espacioVol: "5Gi"
  tolerations: null
  affinity: null
  udpPort: 1745
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"

visitcluster:
  replicas: 1
  image: "gnoss/gnoss.backgroundtask.visitcluster.opencore"
  tag: ""
  pullPolicy: IfNotPresent
  limitsEnabled: true
  limitCpu: 500m
  limitMemory: 600Mi
  requestCpu: 50m
  restartPolicy: Always
  requestMemory: 125Mi
  espacioVol: "5Gi"
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"

####################################
#                                  #
#    VALUES PARA SERVICIOS BACK    #
#                                  #
####################################


generalBack:
  restartPolicy: Always
  pullPolicy: IfNotPresent

mailservice:
  replicas: 1
  image: "gnoss/gnoss.backgroundtask.mail.opencore"
  tag: ""
  pullPolicy: IfNotPresent
  limitsEnabled: true
  limitCpu: 500m
  limitMemory: 600Mi
  requestCpu: 50m
  requestMemory: 125Mi
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"

cacherefresh:
  replicas: 1
  image: "gnoss/gnoss.backgroundtask.cacherefresh.opencore"
  tag: ""
  pullPolicy: IfNotPresent
  limitsEnabled: true
  limitCpu: 500m
  limitMemory: 800Mi
  requestCpu: 50m
  requestMemory: 125Mi
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"


distributor:
  replicas: 1
  image: "gnoss/gnoss.backgroundtask.distributor.opencore"
  tag: ""
  pullPolicy: IfNotPresent
  limitsEnabled: true
  limitCpu: 500m
  limitMemory: 600Mi
  requestCpu: 50m
  requestMemory: 125Mi
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"


searchgraphgeneration:
  replicas: 1
  image: "gnoss/gnoss.backgroundtask.searchgraphgeneration.opencore"
  tag: ""
  pullPolicy: IfNotPresent
  limitsEnabled: true
  limitCpu: 500m
  limitMemory: 800Mi
  requestCpu: 50m
  requestMemory: 125Mi
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"

thumbnailgenerator:
  replicas: 1
  image: "gnoss/gnoss.backgroundtask.thumbnailgenerator.opencore"
  tag: ""
  pullPolicy: IfNotPresent
  limitsEnabled: true
  limitCpu: 500m
  limitMemory: 600Mi
  requestCpu: 50m
  requestMemory: 125Mi
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"

communitywall:
  replicas: 1
  image: "gnoss/gnoss.backgroundtask.communitywall.opencore"
  tag: ""
  pullPolicy: IfNotPresent
  limitsEnabled: true
  limitCpu: 500m
  limitMemory: 500Mi
  requestCpu: 50m
  requestMemory: 125Mi
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"

socialcacherefresh:
  replicas: 1
  image: "gnoss/gnoss.backgroundtask.socialcacherefresh.opencore"
  tag: ""
  pullPolicy: IfNotPresent
  limitsEnabled: true
  limitCpu: 500m
  limitMemory: 500Mi
  requestCpu: 50m
  requestMemory: 125Mi
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"

socialsearchgraphgeneration:
  replicas: 1
  image: "gnoss/gnoss.backgroundtask.socialsearchgraphgeneration.opencore"
  tag: ""
  pullPolicy: IfNotPresent
  limitsEnabled: true
  limitCpu: 500m
  limitMemory: 500Mi
  requestCpu: 50m
  requestMemory: 125Mi
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"

subscriptionsmail:
  replicas: 1
  image: "gnoss/gnoss.backgroundtask.subscriptionsmail.opencore"
  tag: ""
  pullPolicy: IfNotPresent
  limitsEnabled: true
  limitCpu: 500m
  limitMemory: 500Mi
  requestCpu: 50m
  requestMemory: 125Mi
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"

replication:
  replicas: 1
  image: "gnoss/gnoss.backgroundtask.replication.opencore"
  tag: ""
  pullPolicy: IfNotPresent
  limitsEnabled: true
  limitCpu: 500m
  limitMemory: 500Mi
  requestCpu: 50m
  requestMemory: 125Mi
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"
  colasReplicacionMaster:
    - nombreCola: "ColaReplica"
      secretKey: "virtuosoReplicacionMaster1"
  colasReplicacionMasterHome:
    - nombreCola: ColaReplicaHome
      secretKey: virtuosoReplicacionMasterHome1

newsletters:
  replicas: 1
  image: "gnoss/gnoss.backgroundtask.newsletters.opencore"
  tag: ""
  pullPolicy: IfNotPresent
  limitsEnabled: true
  limitCpu: 500m
  limitMemory: 500Mi
  requestCpu: 50m
  requestMemory: 125Mi
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"

userwall:
  replicas: 1
  image: "gnoss/gnoss.backgroundtask.userwall.opencore"
  tag: ""
  pullPolicy: IfNotPresent
  limitsEnabled: true
  limitCpu: 500m
  limitMemory: 500Mi
  requestCpu: 50m
  requestMemory: 125Mi
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"

workflows:
  replicas: 1
  image: "gnoss/gnoss.backgroundtask.workflows.opencore"
  tag: ""
  pullPolicy: IfNotPresent
  limitsEnabled: true
  limitCpu: 500m
  limitMemory: 500Mi
  requestCpu: 50m
  requestMemory: 125Mi
  tolerations: null
  affinity: null
  logLevel:
    default: "Information"
    overrides:
      "Microsoft": "Warning"
      "Microsoft.Hosting.Lifetime": "Information"
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Warning"


######################################
#                                    #
#     VALUES PARA BASES DE DATOS     #
#                                    #
######################################
redis:
  read: "redis"
  master: "redis"
  redisBd: "1"
  redisTimeout: "60"
  recursosBd: "2"
  recursosTimeout: "60"
  liveusuariosBd: "3"
  liveusuariosTimeout: "60"
  bandejaBd: "4"
  bandejaTimeout: "60"
  sparqlBd: "5"
  sparqlTimeout: "60"

##################
#    Postgres    #
##################
postgres:
  enabled: true
