########################
# SOCIAL_CACHE_REFRESH #
########################
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: socialcacherefresh
  name: socialcacherefresh
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.generalBack.replicas }}
  selector:
    matchLabels:
      app: socialcacherefresh
  template:
    metadata:
      labels:
        app: socialcacherefresh
    spec:
      {{ if or (.Values.socialcacherefresh.tolerations) (.Values.general.extraTolerations) }}
      tolerations:
      {{- with .Values.socialcacherefresh.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.general.extraTolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- $cacheAffinity := default dict .Values.socialcacherefresh.affinity }}
      {{- $extraAffinity := default dict .Values.general.extraAffinity }}
      {{- $mergedAffinity := merge $cacheAffinity $extraAffinity }}
      {{- if $mergedAffinity }}
      affinity:
      {{ toYaml $mergedAffinity | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
      {{- if .Values.global.serviceAccountName }}
      serviceAccountName: {{  .Values.global.serviceAccountName | quote }}
      {{- end }}
      {{- with .Values.general.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: socialcacherefresh
        image: {{ printf "%s:%s" .Values.socialcacherefresh.image .Values.socialcacherefresh.tag }}
        imagePullPolicy: {{ .Values.generalBack.pullPolicy }}
        {{- if .Values.socialcacherefresh.limitsEnabled | quote }}
        resources:
          limits:
            memory: {{ .Values.socialcacherefresh.limitMemory }}
            cpu: {{ .Values.socialcacherefresh.limitCpu }}
          requests:
            memory: {{ .Values.socialcacherefresh.requestMemory }}
            cpu: {{ .Values.socialcacherefresh.requestCpu }}
        {{- end }}
        envFrom:
          - configMapRef:
              name: config-gnoss-core
        env:
        - name: acid
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.sql.name }}
              key: {{ .Values.secrets.sql.acid.secretKey }}
        - name: base
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.sql.name }}
              key: {{ .Values.secrets.sql.base.secretKey }}
        - name: virtuosoConnectionString
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.virtuoso.name }}
              key: {{ .Values.secrets.virtuoso.read.secretKey }}
        - name: Virtuoso__Escritura__Virtuoso1
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.virtuoso.name }}
              key: {{ .Values.secrets.virtuoso.write1.secretKey }}
        - name: RabbitMQ__colaServiciosWin
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.rabbitmq.name }}
              key: {{ .Values.secrets.rabbitmq.connectionString.secretKey }}
        - name: RabbitMQ__colaReplicacion
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.rabbitmq.name }}
              key: {{ .Values.secrets.rabbitmq.connectionString.secretKey }}
        - name: intervalo
          value: "100"