###########
#         #
#  OAUTH  #
#         #
###########
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth
  name: oauth
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.oauth.replicas }}
  selector:
    matchLabels:
      app: oauth
  template:
    metadata:
      labels:
        app: oauth
    spec:
      {{ if or (.Values.oauth.tolerations) (.Values.general.extraTolerations) }}
      tolerations:
      {{- with .Values.oauth.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.general.extraTolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- $cacheAffinity := default dict .Values.oauth.affinity }}
      {{- $extraAffinity := default dict .Values.general.extraAffinity }}
      {{- $mergedAffinity := merge $cacheAffinity $extraAffinity }}
      {{- if $mergedAffinity }}
      affinity:
      {{ toYaml $mergedAffinity | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: oauth
        image: {{ printf "%s:%s" .Values.oauth.image (default .Values.general.tag .Values.oauth.tag) }}
        imagePullPolicy: {{ .Values.oauth.pullPolicy }}
        {{- if .Values.oauth.limitsEnabled | quote }}
        resources:
          limits:
            memory: {{ .Values.oauth.limitMemory }}
            cpu: {{ .Values.oauth.limitCpu }}
          requests:
            memory: {{ .Values.oauth.requestMemory }}
            cpu: {{ .Values.oauth.requestCpu }}
        {{- end }}
        envFrom:
          - configMapRef:
              name: config-gnoss-core
        env:
        - name: acid
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.sql.name }}
              key: {{ .Values.secrets.sql.acid.secretKey }}
        - name: base
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.sql.name }}
              key: {{ .Values.secrets.sql.base.secretKey }}
        - name: oauth
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.sql.name }}
              key: {{ .Values.secrets.sql.oauth.secretKey }}
        - name: virtuosoConnectionString
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.virtuoso.name }}
              key: {{ .Values.secrets.virtuoso.read.secretKey }}
        - name: Virtuoso__Escritura__Virtuoso1
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.virtuoso.name }}
              key: {{ .Values.secrets.virtuoso.write1.secretKey }}
        - name: OAuthSettings__RateLimitPermitLimit
          value: {{ .Values.oauth.rateLimitPermitLimit | quote }}
        ports:
        - name: "port-oauth"
          containerPort: {{ .Values.general.apiPort }}
          protocol: TCP
        - name: "management-port"
          containerPort: {{ .Values.general.managementPort }}
          protocol: TCP
        {{- if .Values.general.healthChecksEnabled }}
        livenessProbe:
          httpGet:
            path: /health/live
            port: {{ .Values.general.managementPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: {{ .Values.general.managementPort }}
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
        {{- end }}
        volumeMounts:
        - name: logs-config
          mountPath: /app/logging-config
      volumes:
        - name: logs-config
          configMap:
            name: oauth
      restartPolicy: {{ .Values.oauth.restartPolicy }}
      {{- if .Values.global.serviceAccountName }}
      serviceAccountName: {{  .Values.global.serviceAccountName | quote }}
      {{- end }}
      {{- with .Values.general.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml . | nindent 8 }}
      {{- end }}