{{- if .Values.interno.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: interno
  labels:
    servicio: interno
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: NodePort
  ports:
    - name: "port-int-8080"
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: {{ .Values.interno.debugNodePort }}
  selector:
    app: interno
status:
  loadBalancer: {}
{{- end }}