apiVersion: v1
kind: Service
metadata:
  name: api-interna
  labels:
    servicio: api-interna
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: "port-api"
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: api-interna
status:
  loadBalancer: {}