{{- if .Values.identityserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: identityserver
  labels:
    servicio: identityserver
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: NodePort
  ports:
    - name: "port-identity"
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: {{ .Values.identityserver.debugNodePort }}
  selector:
    app: identityserver
status:
  loadBalancer: {}
{{- end }}