apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-gnoss-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    {{- if .Values.global.basicAuth }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ .Values.secrets.basicAuth.name }}
    {{- end }}
spec:
  ingressClassName: "nginx"
  {{- if .Values.ingress.https }}
  tls:
    - hosts:
      - {{ .Values.global.hosts.web }}
      secretName: {{ .Values.secrets.tls.secretName }}
  {{- end }}
  rules:
  - host: {{ .Values.global.hosts.web }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "web"
            port:
              number: 8080
