##############
#  USERWALL  #
##############
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: userwall
  name: userwall
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.userwall.replicas }}
  selector:
    matchLabels:
      app: userwall
  template:
    metadata:
      labels:
        app: userwall
    spec:
      {{ if or (.Values.userwall.tolerations) (.Values.general.extraTolerations) }}
      tolerations:
      {{- with .Values.userwall.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.general.extraTolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- $cacheAffinity := default dict .Values.userwall.affinity }}
      {{- $extraAffinity := default dict .Values.general.extraAffinity }}
      {{- $mergedAffinity := merge $cacheAffinity $extraAffinity }}
      {{- if $mergedAffinity }}
      affinity:
      {{ toYaml $mergedAffinity | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
      {{- if .Values.global.serviceAccountName }}
      serviceAccountName: {{  .Values.global.serviceAccountName | quote }}
      {{- end }}
      {{- with .Values.general.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: userwall
        image: {{ printf "%s:%s" .Values.userwall.image (default .Values.general.tag .Values.userwall.tag) }}
        imagePullPolicy: {{ .Values.generalBack.pullPolicy }}
        {{- if .Values.userwall.limitsEnabled | quote }}
        resources:
          limits:
            memory: {{ .Values.userwall.limitMemory }}
            cpu: {{ .Values.userwall.limitCpu }}
          requests:
            memory: {{ .Values.userwall.requestMemory }}
            cpu: {{ .Values.userwall.requestCpu }}
        {{- end }}
        ports:
        - name: "management-port"
          containerPort: {{ .Values.general.managementPort }}
          protocol: TCP
        {{- if .Values.general.healthChecksEnabled }}
        livenessProbe:
          httpGet:
            path: /health/live
            port: {{ .Values.general.managementPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: {{ .Values.general.managementPort }}
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
        {{- end }}
        envFrom:
          - configMapRef:
              name: config-gnoss-core
        env:
        - name: acid
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.sql.name }}
              key: {{ .Values.secrets.sql.acid.secretKey }}
        - name: base
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.sql.name }}
              key: {{ .Values.secrets.sql.base.secretKey }}
        - name: virtuosoConnectionString
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.virtuoso.name }}
              key: {{ .Values.secrets.virtuoso.read.secretKey }}
        - name: Virtuoso__Escritura__Virtuoso1
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.virtuoso.name }}
              key: {{ .Values.secrets.virtuoso.write1.secretKey }}
        - name: RabbitMQ__colaServiciosWin
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.rabbitmq.name }}
              key: {{ .Values.secrets.rabbitmq.connectionString.secretKey }}
        - name: RabbitMQ__colaReplicacion
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.rabbitmq.name }}
              key: {{ .Values.secrets.rabbitmq.connectionString.secretKey }}
        - name: scopeIdentity
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.identity.name }}
              key: {{ .Values.secrets.identity.scope.secretKey }}
        - name: clientIDIdentity
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.identity.name }}
              key: {{ .Values.secrets.identity.clientID.secretKey }}
        - name: clientSecretIdentity
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.identity.name }}
              key: {{ .Values.secrets.identity.clientSecret.secretKey }}
        - name: intervalo
          value: "100"
        volumeMounts:
        - name: logs-config
          mountPath: /app/logging-config
      volumes:
        - name: logs-config
          configMap:
            name: userwall