###############
# REPLICATION #
###############
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: replication
  name: replication
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.replication.replicas }}
  selector:
    matchLabels:
      app: replication
  template:
    metadata:
      labels:
        app: replication
    spec:
      {{ if or (.Values.replication.tolerations) (.Values.general.extraTolerations) }}
      tolerations:
      {{- with .Values.replication.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.general.extraTolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- $cacheAffinity := default dict .Values.replication.affinity }}
      {{- $extraAffinity := default dict .Values.general.extraAffinity }}
      {{- $mergedAffinity := merge $cacheAffinity $extraAffinity }}
      {{- if $mergedAffinity }}
      affinity:
      {{ toYaml $mergedAffinity | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
      {{- if .Values.global.serviceAccountName }}
      serviceAccountName: {{  .Values.global.serviceAccountName | quote }}
      {{- end }}
      {{- with .Values.general.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: replication
        image: {{ printf "%s:%s" .Values.replication.image (default .Values.general.tag .Values.replication.tag) }}
        imagePullPolicy: {{ .Values.generalBack.pullPolicy }}
        {{- if .Values.replication.limitsEnabled | quote }}
        resources:
          limits:
            memory: {{ .Values.replication.limitMemory }}
            cpu: {{ .Values.replication.limitCpu }}
          requests:
            memory: {{ .Values.replication.requestMemory }}
            cpu: {{ .Values.replication.requestCpu }}
        {{- end }}
        ports:
        - name: "management-port"
          containerPort: {{ .Values.general.managementPort }}
          protocol: TCP
        {{- if .Values.general.healthChecksEnabled }}
        livenessProbe:
          httpGet:
            path: /health/live
            port: {{ .Values.general.managementPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: {{ .Values.general.managementPort }}
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
        {{- end }}
        envFrom:
          - configMapRef:
              name: config-gnoss-core
        env:
        - name: acid
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.sql.name }}
              key: {{ .Values.secrets.sql.acid.secretKey }}
        - name: base
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.sql.name }}
              key: {{ .Values.secrets.sql.base.secretKey }}
        - name: virtuosoConnectionString
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.virtuoso.name }}
              key: {{ .Values.secrets.virtuoso.read.secretKey }}
        - name: Virtuoso__Escritura__Virtuoso1
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.virtuoso.name }}
              key: {{ .Values.secrets.virtuoso.write1.secretKey }}
        {{- with .Values.replication.colasReplicacionMaster }}
        {{- range . }}
        - name: {{ printf "ColaReplicacionMaster_%s" .nombreCola }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.secrets.virtuoso.name }}
              key: {{ .secretKey }}
        {{- end }}
        {{- end }}

        {{- with .Values.replication.colasReplicacionMasterHome }}
        {{- range . }}
        - name: {{ printf "ColaReplicacionMasterHome__%s" .nombreCola }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.secrets.virtuoso.name }}
              key: {{ .secretKey }}
        {{- end }}
        {{- end }}
        - name: RabbitMQ__colaServiciosWin
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.rabbitmq.name }}
              key: {{ .Values.secrets.rabbitmq.connectionString.secretKey }}
        - name: RabbitMQ__colaReplicacion
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.rabbitmq.name }}
              key: {{ .Values.secrets.rabbitmq.connectionString.secretKey }}
        - name: intervalo
          value: "100"
        volumeMounts:
        - name: logs-config
          mountPath: /app/logging-config
      volumes:
        - name: logs-config
          configMap:
            name: replication