apiVersion: v1
kind: ConfigMap
metadata:
  name: newsletters
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Error"
        }
      },
      "Serilog": {
        "MinimumLevel": {
          "Default": {{ .Values.newsletters.logLevel.default | quote }},
          "Override": {
            {{- $first := true }}
            {{- range $namespace, $level := .Values.newsletters.logLevel.overrides }}
            {{- if not $first }},{{ end }}
            {{ $namespace | quote }}: {{ $level | quote }}
            {{- $first = false }}
            {{- end }}
          }
        }
      }
    }