##################################
# SOCIAL_SEARCH_GRAPH_GENERATION #
##################################
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: socialsearchgraphgeneration
  name: socialsearchgraphgeneration
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.socialsearchgraphgeneration.replicas }}
  selector:
    matchLabels:
      app: socialsearchgraphgeneration
  template:
    metadata:
      labels:
        app: socialsearchgraphgeneration
    spec:
      {{ if or (.Values.socialsearchgraphgeneration.tolerations) (.Values.general.extraTolerations) }}
      tolerations:
      {{- with .Values.socialsearchgraphgeneration.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.general.extraTolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- $cacheAffinity := default dict .Values.socialsearchgraphgeneration.affinity }}
      {{- $extraAffinity := default dict .Values.general.extraAffinity }}
      {{- $mergedAffinity := merge $cacheAffinity $extraAffinity }}
      {{- if $mergedAffinity }}
      affinity:
      {{ toYaml $mergedAffinity | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
      {{- if .Values.global.serviceAccountName }}
      serviceAccountName: {{  .Values.global.serviceAccountName | quote }}
      {{- end }}
      {{- with .Values.general.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: socialsearchgraphgeneration
        image: {{ printf "%s:%s" .Values.socialsearchgraphgeneration.image (default .Values.general.tag .Values.socialsearchgraphgeneration.tag) }}
        imagePullPolicy: {{ .Values.generalBack.pullPolicy }}
        {{- if .Values.socialsearchgraphgeneration.limitsEnabled | quote }}
        resources:
          limits:
            memory: {{ .Values.socialsearchgraphgeneration.limitMemory }}
            cpu: {{ .Values.socialsearchgraphgeneration.limitCpu }}
          requests:
            memory: {{ .Values.socialsearchgraphgeneration.requestMemory }}
            cpu: {{ .Values.socialsearchgraphgeneration.requestCpu }}
        {{- end }}
        ports:
        - name: "management-port"
          containerPort: {{ .Values.general.managementPort }}
          protocol: TCP
        {{- if .Values.general.healthChecksEnabled }}
        livenessProbe:
          httpGet:
            path: /health/live
            port: {{ .Values.general.managementPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: {{ .Values.general.managementPort }}
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
        {{- end }}
        envFrom:
          - configMapRef:
              name: config-gnoss-core
        env:
        - name: acid
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.sql.name }}
              key: {{ .Values.secrets.sql.acid.secretKey }}
        - name: base
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.sql.name }}
              key: {{ .Values.secrets.sql.base.secretKey }}
        - name: virtuosoConnectionString
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.virtuoso.name }}
              key: {{ .Values.secrets.virtuoso.read.secretKey }}
        - name: Virtuoso__Escritura__Virtuoso1
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.virtuoso.name }}
              key: {{ .Values.secrets.virtuoso.write1.secretKey }}
        - name: RabbitMQ__colaServiciosWin
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.rabbitmq.name }}
              key: {{ .Values.secrets.rabbitmq.connectionString.secretKey }}
        - name: RabbitMQ__colaReplicacion
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.rabbitmq.name }}
              key: {{ .Values.secrets.rabbitmq.connectionString.secretKey }}
        - name: scopeIdentity
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.identity.name }}
              key: {{ .Values.secrets.identity.scope.secretKey }}
        - name: clientIDIdentity
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.identity.name }}
              key: {{ .Values.secrets.identity.clientID.secretKey }}
        - name: clientSecretIdentity
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.identity.name }}
              key: {{ .Values.secrets.identity.clientSecret.secretKey }}
        - name: intervalo
          value: "100"
        volumeMounts:
        - name: logs-config
          mountPath: /app/logging-config
      volumes:
        - name: logs-config
          configMap:
            name: socialsearchgraphgeneration