
# Web 
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gnoss-routes
  namespace: {{ .Values.global.namespace }}
spec:
  parentRefs:
  - name: gnoss-gateway
    namespace: {{ .Values.global.namespace }}
    sectionName: {{ if .Values.ingress.https }}https{{ else }}http{{ end }}
  hostnames:
  - {{ .Values.ingress.hostWeb }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: nginx
      port: 8080


# Servicios
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gnoss-routes
  namespace: {{ .Values.global.namespace }}
spec:
  parentRefs:
  - name: gnoss-gateway
    namespace: {{ .Values.global.namespace }}
    sectionName: {{ if .Values.ingress.https }}https{{ else }}http{{ end }}
  hostnames:
  - {{ .Values.ingress.hostServicios }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /facetas
    backendRefs:
    - name: facetas
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: /resultados
    backendRefs:
    - name: resultados
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: /login
    backendRefs:
    - name: login
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: /autocompletar
    backendRefs:
    - name: autocompletar
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: /autocompletaretiquetas
    backendRefs:
    - name: etiquetadoautomatico
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: /api
    backendRefs:
    - name: api
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: /interno/content
    backendRefs:
    - name: interno
      port: 8080
  