{{- if .Values.web.logs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-web-logs"
  namespace: {{ .Release.Namespace | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.global.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.web.logs.size | quote }}
{{- end }}