apiVersion: v1
kind: Service
metadata:
  name: oauth
  labels:
    servicio: oauth
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: "port-oauth"
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: oauth
status:
  loadBalancer: {}