apiVersion: v1
kind: Service
metadata:
  name: "postgres"
  namespace: {{ .Values.global.namespace }}
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
  - name: sql
    protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: virtuoso
  namespace: {{ .Values.global.namespace }}
  labels:
    app: virtuoso
spec:
  type: ClusterIP
  ports:
  - name: sparql
    protocol: TCP
    port: 8890
    targetPort: 8890
  - name: isql
    protocol: TCP
    port: 1111
    targetPort: 1111
  selector:
    app.gnoss: virtuoso
---
apiVersion: v1
kind: Service
metadata:
  name: virtuoso1
  namespace: {{ .Values.global.namespace }}
  labels:
    app: virtuoso1
spec:
  type: ClusterIP
  ports:
  - name: sparql
    protocol: TCP
    port: 8890
    targetPort: 8890
  - name: isql
    protocol: TCP
    port: 1111
    targetPort: 1111
  selector:
    app: virtuoso1
---
apiVersion: v1
kind: Service
metadata:
  name: virtuoso2
  namespace: {{ .Values.global.namespace }}
  labels:
    app: virtuoso2
spec:
  type: ClusterIP
  ports:
  - name: sparql
    protocol: TCP
    port: 8890
    targetPort: 8890
  - name: isql
    protocol: TCP
    port: 1111
    targetPort: 1111
  selector:
    app: virtuoso2
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.global.namespace }}
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    app: redis

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: epmd
    protocol: TCP
    port: 4369
    targetPort: 4369
  - name: cluster-rpc
    protocol: TCP
    port: 25672
    targetPort: 25672
  - name: amqp
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: administrador
    protocol: TCP
    port: 15672
    targetPort: 15672
  selector:
    app: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-np
  namespace: {{ .Values.global.namespace }}
spec:
  type: NodePort
  sessionAffinity: None
  ports:
  - name: amqp
    protocol: TCP
    port: 5672
    targetPort: 5672
  selector:
    app: rabbitmq
