apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    servicio: web
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: "port-web"
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: web
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: login
  labels:
    servicio: login
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: "port-login"
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: login
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    servicio: facetas
  name: facetas
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: "port-facetas"
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: facetas
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: resultados
  labels:
    servicio: resultados
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: "port-results"
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: results
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: interno
  labels:
    servicio: interno
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: "port-int-8080"
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: interno
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: archivo
  labels:
    servicio: archivo
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: "port-ontologias"
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: ontologias
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: documents
  labels:
    servicio: documents
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: "port-document"
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: documents
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: autocompletar
  labels:
    servicio: autocompletar
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: "port-autocomple"
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: autocompletar
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: despliegues
  labels:
    servicio: despliegues
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: "port-despliegue"
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: despliegues
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    servicio: api
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: "port-api"
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: api
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: api-interna
  labels:
    servicio: api-interna
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: "port-api"
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: api-interna
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: oauth
  labels:
    servicio: oauth
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: "port-oauth"
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: oauth
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: static
  labels:
    servicio: static
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: "port-static"
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: static
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: identityserver
  labels:
    servicio: identityserver
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: "port-identity"
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: identityserver
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  name: deploy
  labels:
    servicio: deploy
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: "port-deploy"
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: deploy
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  name: etiquetadoautomatico
  labels:
    servicio: etiquetadoautomatico
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: "port-etiquetado"
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: etiquetadoautomatico
status:
  loadBalancer: {}