apiVersion: v1
kind: Service
metadata:
  name: virtuoso2
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: virtuoso2
spec:
  type: ClusterIP
  ports:
  - name: sparql
    protocol: TCP
    port: 8890
    targetPort: 8890
  - name: isql
    protocol: TCP
    port: 1111
    targetPort: 1111
  selector:
    app: virtuoso2