apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: services-gnoss-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
spec:
  ingressClassName: "nginx"
  {{- if .Values.ingress.https }}
  tls:
    - hosts:
      - {{ .Values.global.hosts.services }}
      secretName: {{ .Values.secrets.tls.secretName }}
  {{- end }}
  rules:
### SERVICIOS ###
  - host: {{ .Values.global.hosts.services}}
    http:
      paths:
      {{- if .Values.facetas.enabled }}
      - path: /facetas(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: facetas
            port:
              number: 8080
      {{- end }}
      {{- if .Values.results.enabled }}
      - path: /resultados(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: resultados
            port:
              number: 8080
      {{- end }}
      {{- if .Values.login.enabled }}
      - path: /login(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: login
            port:
              number: 8080
      {{- end }}
      {{- if .Values.autocompletar.enabled }}
      - path: /autocompletar(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: autocompletar
            port:
              number: 8080
      {{- end }}
      {{- if .Values.etiquetadoautomatico.enabled }}
      - path: /autocompletaretiquetas(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: etiquetadoautomatico
            port:
              number: 8080
      {{- end }}
      {{- if .Values.api.enabled }}
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: api
            port:
              number: 8080
      {{- end }}
      {{- if .Values.despliegues.enabled }}
      - path: /despliegues(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: despliegues
            port:
              number: 8080
      {{- end }}
