###################
#                 #
#  AUTOCOMPLETAR  #
#                 #
###################
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: autocompletar
  name: autocompletar
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.autocompletar.replicas }}
  selector:
    matchLabels:
      app: autocompletar
  template:
    metadata:
      labels:
        app: autocompletar
    spec:
      {{ if or (.Values.autocompletar.tolerations) (.Values.general.extraTolerations) }}
      tolerations:
      {{- with .Values.autocompletar.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.general.extraTolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- $cacheAffinity := default dict .Values.autocompletar.affinity }}
      {{- $extraAffinity := default dict .Values.general.extraAffinity }}
      {{- $mergedAffinity := merge $cacheAffinity $extraAffinity }}
      {{- if $mergedAffinity }}
      affinity:
      {{ toYaml $mergedAffinity | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: autocompletar
        image: {{ printf "%s:%s" .Values.autocompletar.image .Values.autocompletar.tag }}
        imagePullPolicy: {{ .Values.autocompletar.pullPolicy }}
        {{- if .Values.autocompletar.limitsEnabled | quote }}
        resources:
          limits:
            memory: {{ .Values.autocompletar.limitMemory }}
            cpu: {{ .Values.autocompletar.limitCpu }}
          requests:
            memory: {{ .Values.autocompletar.requestMemory }}
            cpu: {{ .Values.autocompletar.requestCpu }}
        {{- end }}
        envFrom:
          - configMapRef:
              name: config-gnoss-core
        env:
        - name: acid
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.sql.name }}
              key: {{ .Values.secrets.sql.acid.secretKey }}
        - name: base
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.sql.name }}
              key: {{ .Values.secrets.sql.base.secretKey }}
        - name: virtuosoConnectionString
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.virtuoso.name }}
              key: {{ .Values.secrets.virtuoso.read.secretKey }}
        - name: Virtuoso__Escritura__Virtuoso1
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.virtuoso.name }}
              key: {{ .Values.secrets.virtuoso.write1.secretKey }}
        - name: Servicios__urlBase
          value: {{ printf "%s://%s" .Values.ingress.schema_servicios .Values.global.hosts.services }}
        ports:
        - name: "port-autocomple"
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: logs-config
          mountPath: /app/logging-config
      volumes:
        - name: logs-config
          configMap:
            name: autocompletar
      restartPolicy: {{ .Values.autocompletar.restartPolicy }}
      {{- if .Values.global.serviceAccountName }}
      serviceAccountName: {{  .Values.global.serviceAccountName | quote }}
      {{- end }}
      {{- with .Values.general.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml . | nindent 8 }}
      {{- end }}