name: Push Helm Chart
on:
  push:
    tags: ['*']

permissions:
  contents: read   
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check version matches tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          CHART_VERSION=$(helm show chart . | grep '^version:' | awk '{print $2}')

          if [ "$TAG" != "$CHART_VERSION" ]; then
            echo "La Tag ($TAG) no coincide con la version del Chart.yaml: ($CHART_VERSION)"
            exit 1
          fi

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN  }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Package and push
        run: |
          helm package .
          helm push *.tgz oci://ghcr.io/${{ github.repository_owner }}