{{- if .Values.ontologias.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ontologias 
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: ontologias 
spec:
  replicas: {{ .Values.ontologias.replicas }}
  serviceName: "archivo"
  selector:
    matchLabels:
      app: ontologias 
  template:
    metadata:
      labels:
        app: ontologias 
    spec:
      {{ if or (.Values.ontologias.tolerations) (.Values.general.extraTolerations) }}
      tolerations:
      {{- with .Values.ontologias.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.general.extraTolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- $cacheAffinity := default dict .Values.ontologias.affinity }}
      {{- $extraAffinity := default dict .Values.general.extraAffinity }}
      {{- $mergedAffinity := merge $cacheAffinity $extraAffinity }}
      {{- if $mergedAffinity }}
      affinity:
      {{ toYaml $mergedAffinity | nindent 8 }}
      {{- end }}
      securityContext:
        runAsUser: {{ .Values.general.user }}
        runAsGroup: {{ .Values.general.group }}
        fsGroup: {{ .Values.general.group }}
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: ontologias 
        image: {{ printf "%s:%s" .Values.ontologias.image (default .Values.general.tag .Values.ontologias.tag) }}
        imagePullPolicy: {{ .Values.generalstatefulset.pullPolicy }}
        {{- if .Values.ontologias.limitsEnabled | quote }}
        resources:
          limits:
            memory: {{ .Values.ontologias.limitMemory }}
            cpu: {{ .Values.ontologias.limitCpu }}
          requests:
            memory: {{ .Values.ontologias.requestMemory }}
            cpu: {{ .Values.ontologias.requestCpu }}
        {{- end }}
        envFrom:
          - configMapRef:
              name: config-gnoss-core
        env:
        - name: acid
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.sql.name }}
              key: {{ .Values.secrets.sql.acid.secretKey }}
        - name: base
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.sql.name }}
              key: {{ .Values.secrets.sql.base.secretKey }}
        - name: virtuosoConnectionString
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.virtuoso.name }}
              key: {{ .Values.secrets.virtuoso.read.secretKey }}
        - name: Virtuoso__Escritura__Virtuoso1
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.virtuoso.name }}
              key: {{ .Values.secrets.virtuoso.write1.secretKey }}
        - name: rutaOntologias
          value: "Ontologias/Archivos"
        ports:
        - name: "port-ontologias"
          containerPort: {{ .Values.general.apiPort }}
          protocol: TCP
        - name: "management-port"
          containerPort: {{ .Values.general.managementPort }}
          protocol: TCP
        {{- if .Values.general.healthChecksEnabled }}
        livenessProbe:
          httpGet:
            path: /health/live
            port: {{ .Values.general.managementPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: {{ .Values.general.managementPort }}
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
        {{- end }}
        volumeMounts:
        - name: {{ include "gnoss.persistentVolumeName" . }}
          mountPath: /app/Ontologias
          subPath: ontologias
        - name: logs-config
          mountPath: /app/logging-config
      volumes:
        - name: logs-config
          configMap:
            name: ontologias
      {{- if .Values.global.serviceAccountName }}
      serviceAccountName: {{  .Values.global.serviceAccountName | quote }}
      {{- end }}
      {{- with .Values.general.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: {{ include "gnoss.persistentVolumeName" . }}
      namespace: {{ .Release.Namespace | quote }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.global.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.ontologias.espacioVol }}
{{- end }}